CREATE TABLE User(
   Id_User INT AUTO_INCREMENT,
   Username VARCHAR(50)  NOT NULL,
   Password VARCHAR(50)  NOT NULL,
   Email VARCHAR(50)  NOT NULL,
   PRIMARY KEY(Id_User)
);

CREATE TABLE Player(
   Id_Player INT AUTO_INCREMENT,
   Name VARCHAR(50)  NOT NULL,
   Id_User INT NOT NULL,
   PRIMARY KEY(Id_Player),
   FOREIGN KEY(Id_User) REFERENCES User(Id_User)
);

CREATE TABLE Score(
   Id_Score INT AUTO_INCREMENT,
   Score INT NOT NULL,
   Id_Player INT NOT NULL,
   PRIMARY KEY(Id_Score),
   FOREIGN KEY(Id_Player) REFERENCES Player(Id_Player)
);
